# Generated by Django 3.2.6 on 2021-08-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_crud', '0002_remove_create_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create',
            new_name='task_create',
        ),
    ]
